Network Type missing
gomorpheus/morpheus-xenserver-plugin pull request #45
Opened 2024-05-27 09:48 UTC by razi-ahmad1

2024-05-27 23:08 UTC, ddeyoung requested changes

2024-05-27 23:08 UTC, ddeyoung commented on src/main/groovy/com/morpheusdata/xen/XenserverCloudProvider.groovy
need dockerBridge, host, overlay, and xenNetwork to be returned here.

2024-05-28 07:27 UTC, razi-ahmad1 commented on src/main/groovy/com/morpheusdata/xen/XenserverCloudProvider.groovy
@ddeyoung code updated as suggested.

2024-05-28 12:39 UTC, ddeyoung requested changes

2024-05-28 12:39 UTC, ddeyoung commented on src/main/groovy/com/morpheusdata/xen/XenserverCloudProvider.groovy
xenNetwork needs created here.

2024-05-28 12:47 UTC, razi-ahmad1 commented on src/main/groovy/com/morpheusdata/xen/XenserverCloudProvider.groovy
@ddeyoung changes has been done as suggested

2024-05-28 12:48 UTC, merged