Library Node form broken
gomorpheus/morpheus-xenserver-plugin pull request #50
Opened 2024-05-31 10:18 UTC by razi-ahmad1

2024-05-31 12:45 UTC, ddeyoung requested changes
There are slight differences from embedded. Please review and fix.

2024-05-31 14:34 UTC, ddeyoung requested changes

2024-05-31 14:34 UTC, ddeyoung commented on src/main/groovy/com/morpheusdata/xen/XenserverProvisionProvider.groovy
> +				noSelection: 'Select',
editable is missing.

2024-06-03 15:59 UTC, razi-ahmad1 commented on src/main/groovy/com/morpheusdata/xen/XenserverProvisionProvider.groovy
> +				noSelection: 'Select',
@ddeyoung changes has made as suggested

2024-06-04 15:25 UTC, ddeyoung approved these changes

2024-06-04 15:25 UTC, merged